@baseUrl = http://localhost:3000/api


GET http://localhost:3000/api/v1/test HTTP/1.1

###

GET http://localhost:3000/api/v1/test/custom-query HTTP/1.1

###

DELETE http://localhost:3000/api/v1/test/9 HTTP/1.1

###

GET http://localhost:3000/api/v1/test/7 HTTP/1.1

###
PUT http://localhost:3000/api/v1/test/8 HTTP/1.1
Content-Type: application/json

{
    "title": "sample712"
}
###

@authToken = {{login.response.headers.X-AuthToken}}
###

POST http://localhost:3000/api/v1/test HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "sample",
    "text": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###

# @name login
POST {{baseUrl}}/v1/loginAction HTTP/1.1
Content-Type: application/json

{
    "title": "sample",
    "text": "Wed, 21 Oct 2015 18:27:50 GMT"
}


